name: Veracode Upload And Scan

on:
  push:
    branches:
      - main

jobs:
  veracode-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Veracode Upload and Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          # Required parameters
          appname: Vince-Hinojosa-Veracode/Juice-Shop
          createprofile: true
          filepath: ./path/to/artifact.zip
          version: ${{ github.run_id }}-${{ github.run_number }}
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}

          # Optional parameters
          createsandbox: false
          scantimeout: 60
          criticality: Medium
          deleteincompletescan: true
          scanpollinginterval: 120
          javawrapperversion: latest
          debug: false
          includenewmodules: true
          
      - name: Verify Veracode Scan
        run: |
          java -jar VeracodeJavaAPI.jar \
            -filepath ./path/to/artifact.zip \
            -version "${{ github.run_id }}-${{ github.run_number }}" \
            -action "uploadandscan" \
            -appname "Vince-Hinojosa-Veracode/Juice-Shop" \
            -vid "${{ secrets.VERACODE_API_ID }}" \
            -vkey "${{ secrets.VERACODE_API_KEY }}" \
            -createsandbox "false" \
            -scantimeout "60" \
            -autoscan "true" \
            -criticality "Medium" \
            -scanallnonfataltoplevelmodules "false" \
            -deleteincompletescan "true" \
            -scanpollinginterval "120" \
            -createprofile "true" \
            -includenewmodules "true" \
            -debug "false"
